# Generated by Django 2.1.5 on 2019-02-08 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageview',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='presentation.Image'),
        ),
    ]
