# Generated by Django 2.1.7 on 2019-06-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0005_game_game_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='time_limit',
            field=models.IntegerField(default=120),
        ),
    ]
