# Generated by Django 2.1.7 on 2019-06-25 15:54
from random import choices
from string import ascii_uppercase

from django.db import migrations, models


def gen_uuid(apps, schema_editor):
    Game = apps.get_model('presentation', 'Game')
    for row in Game.objects.all():
        row.game_id = ''.join(choices(ascii_uppercase, k=5))
        row.save(update_fields=['game_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0006_game_time_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_id',
            field=models.CharField(max_length=5, unique=True, null=True),
        ),
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='game',
            name='game_id',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
