# Generated by Django 2.1.7 on 2019-06-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0007_game_game_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='round_start_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
